### ISSUE TITLE
Won't download when streamer starts live streaming

### ISSUE THREAD

**Issue by thegamingstig** [youcantgetme/TwitchLiveLeecher#1]
I left the program on 15mins prior to the start of the stream. It fail to detect the streamer was live for over 10 mins

**Comment by youcantgetme** [comment]
Could you paste the line you are running at "run.bat" ?
Also have you seen the cmd window with streamer ID in the title, "[INFO] Listening {Streamer ID}" inside window?

**Comment by thegamingstig** [comment]
@start php\php.exe live_leecher.php djddoll

I do see the streamer ID in the title. It just constantly kept listening several lines even after the steamer was streaming. I had to close and reopen the run.bat just to get it to start the download

**Comment by youcantgetme** [comment]
Thanks for reporting, I'm not sure that new twitch AD mechanism will effect the way script fetching token or not.
But you can try shorten the waiting time between every check, by editing **IDLE_TIME** in the **live_leecher.php** from 180 seconds to length you want.
It is still strange that script unable to detect channel has been streaming for 10 minutes that means checking 3 times at least, I will try to collect some feedback from others.
Please do update if you are experiencing record is not starting after 1 or 2 waiting periods again.

**Comment by thegamingstig** [comment]
Tried running this program again. Streamer had a quick DC and reconnect. The program did not detect the reconnection. I had the idle time previously change to 30 seconds. Had to close and restart the program.

**Comment by youcantgetme** [comment]
> Tried running this program again. Streamer had a quick DC and reconnect. The program did not detect the reconnection. I had the idle time previously change to 30 seconds. Had to close and restart the program.

New method introduce to detect live status, although the original is to fetch M3U8 list directly. 
So if the root cause stay the same, I guess will resulting in success getting live status then failed at fetching M3U8 list.
Still, a new breakpoint to help identify the problem.

https://github.com/youcantgetme/TwitchLiveLeecher/commit/6d6a6c89550f578f817d2cd2e53bd61de188cbd0

**Comment by youcantgetme** [comment]
I found out that token timeout period 1 hour I used is longer than Twitch token timeout 20 minutes, which I believe is longer before.
So script will think channel is offline due to request is failed regardless the cause of fail in previous detecting method.

With requesting channel status via GQL API, I can remove time out and getting new token only when channel is live, so no expired token anymore.

There are lots more actions should be added when timeout mechanism is introduced, sorry for the inconvenience.

https://github.com/youcantgetme/TwitchLiveLeecher/releases/tag/v1.20
